2024-10-10 15:50:44,404 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Учеба Python\Projects\pythonProject\012_modul\tests_12_4\tests_12_4.py", line 30, in test_run
    run = rn.Runner(name=2, speed=5)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Учеба Python\Projects\pythonProject\012_modul\tests_12_4\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-10 15:50:44,405 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Учеба Python\Projects\pythonProject\012_modul\tests_12_4\tests_12_4.py", line 17, in test_walk
    run = rn.Runner(name='Вося', speed=-5)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Учеба Python\Projects\pythonProject\012_modul\tests_12_4\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
